### ISSUE TITLE
1.18.2 Flux Networks issue

### ISSUE THREAD

**Issue by ixam22** [DenisMasterHerobrine/AngelRing#32]
Wireless charging is charging the ring full.
if energy drops or if it get loaded fully this error is showing
![grafik](https://user-images.githubusercontent.com/72611276/174885877-c8ce65aa-f5e6-4ec7-b982-4d0c5714dc7e.png)

**Comment by DenisMasterHerobrine** [comment]
I have fixed this in 2.0.1. Check in your modpack if this fixes this. Feel free to reopen if something goes wrong again with Flux Networks. I couldn't reproduce it properly, but fixed the behaviour I got accidentally. Thank you for the report!

**Comment by DenisMasterHerobrine** [comment]
> Hi there, I'm playing Direwolf20 1.18 and the modpack just got updated to its 1.6.1 version that includes version 2.0.1 of Angel Rings that should fix this.
> 
> But the bug is still present there. It's still present even when testing in an instance that only has Angel Rings, Flux Networks and Mekanism (for a creative power source). The issue between Angel Rings and Flux Networks seems to come from the Flux Controller that has its Bypass Limit feature activated and only when its buffer goes above 2 billion FE or so. I'm guessing that it goes wrong at the 32 bit signed integer limit of 2,147,483,647.
> 
> I'll also be making a post on the Flux Networks GH to see if the problem stems from that mod, because as a player I simply cannot tell from what I see in-game.

Hi, sorry for the late response, there were no info at the issue and in v2.0.1 there was a **blind** fix since I didn't knew what caused that, but I managed to somehow get another behaviour that seemed to be fixed v2.0.1. However this was already fixed in v2.0.2, I haven't seen your message since the issue was closed and only late emails from GH said that there was a message, so there were more chances to speed up the fix by opening a new issue since this issue doesn't described the Bypass Limit thing. So as for now should work as intended. Sorry for misunderstanding and a bit late fix.
