### ISSUE TITLE
[Crash] Angelring 2.x.x Crashes Direwolf20 1.18.2 on boot

### ISSUE THREAD

**Issue by TheonlyTazz** [DenisMasterHerobrine/AngelRing#37]
**Mod Version**
angelring-1.18.2-2.x.x.jar

**Forge Version**
40.1.54

**Modpack**
FTB Presents Direwolf20 1.7.0 (in Dev)

**Describe Issue**
While working on an Update for Direwolf20, i tried updating Angelring from 1.5.0 to 2.0+ and it keeps crashing the instance.

**Crashlog**
[Crashlog](https://gist.github.com/TheonlyTazz/49e0752f964cc2819748264c5e41bdc6)

**Comment by DenisMasterHerobrine** [comment]
Hi. Thanks for the report. Just tested with fully clean Forge 40.1.54 instance and downloading Angel Ring from CurseForge and try to do random stuff like switching the dimensions or do something related to ExperienceDisplayUtils which fixes the MC issue related to experience issues when switching between dimensions. Cannot reproduce the crash at all.

Seems that crashlog is relating to a missing `.class` file. The JAR file you using in your pack seems to be corrupted somehow?
To be correct the crashlog relates to a `ClassNotFoundException` which is caused by missing `dev\denismasterherobrine\angelring\utils\ExperienceDisplayUtils.class` file in the jar. Check if the file even exists in the jar, if not, then redownload it manually from CF. It should work fine. Also you can check the MD5 hash of the jar used and make sure it's identical to `97E6D4DB69525200BF0B4C10F30509B5`. You can use Powershell or other tools to find out MD5 hash of this file. (the hash also can be found on CurseForge downloads page)

Also there could be a possible mod incompatibility when some class loader optimizations are introduced in the pack and something went wrong. 
Also you can provide a jar you're using to reproduce the crash, so I could find out what's wrong. In any case you can also contact me through Discord if you want to help me to find the reason of the crash if redownloading the mod causes the same crash or doesn't help at all, but MD5 is identical.

I will leave this issue open for some time, but I assume thats the issue isn't on my end.

**Comment by TheonlyTazz** [comment]
i actually just reinstalled my dev instance and it seems to have fixed itself, i just totally forgot to close the issue... probably something went wrong while syncing with the repo 

thanks for your response tho!

**Comment by DenisMasterHerobrine** [comment]
No problem, however, thanks for letting me know. I've sorted the issue as "other" since it's not a bug as of now.
