### ISSUE TITLE
not problem

### ISSUE THREAD

**Issue by FarmLander** [DenisMasterHerobrine/AngelRing#38]
Hello, I made Russian localization for the mod! I did it purely for my server, but I decided to share it with you. I don't understand GitHub, so I posted it here :(

https://pastebin.com/GxQ8V2TR
ru_ru file

**Comment by DenisMasterHerobrine** [comment]
At the moment, while I accept localizations through Pull Request, this localization requires some changes since the original naming was taken from ExU2, this localization can be interpreted in many ways and there are lots of possible variations of this translation and to not annoy people I didn't added this localization yet even I know the language.
