### ISSUE TITLE
[1.19.2] Thermal Rings have no recipes

### ISSUE THREAD

**Issue by Saereth** [DenisMasterHerobrine/AngelRing#43]
Thermal Expansion has update to 1.19.2 and with it the thermal variants for angel rings now show in JEI but they don't have a recipe. I can add recipes as a packmaker but if this is something you'll be adding I'll hold off.

**Comment by DenisMasterHerobrine** [comment]
Hello, thanks for notifying me about it. I haven't changed them since 1.18.2 release of Thermal Series and seems they work properly on 1.18.2. Seems some items got refactored and I need to edit the 1.19.2 recipes to make them work since they're added the same way as datapack ones. I'll fix it as soon as I get back from hiatus. (probably in a few days, I have some stuff that needs to be sorted first)

**Comment by DenisMasterHerobrine** [comment]
Oops, seems I forgot to just rename an item due to a small refactoring when switching to a triple (1.16/1.18/1.19) version support.

Should be fixed in v2.1.5. When it comes out on CF, I'll close the issue and comment in the original thread.

**Comment by DenisMasterHerobrine** [comment]
Angel Ring v2.1.5 is now available on CF. Feel free to reopen this issue in case it still persists.

**Comment by hallool** [comment]
on 1.20.1 same bug ony angel ring and energetic angel ring have a recepie
