### ISSUE TITLE
1.20.1 recepie bug

### ISSUE THREAD

**Issue by hallool** [DenisMasterHerobrine/AngelRing#50]
only angel ring and energetic angel ring have a recepie 

leadstone,hardened,rainforced and resonant dont have any recepie

**Comment by DenisMasterHerobrine** [comment]
This is not a bug, it is intended, since the other rings require [Thermal Expansion](https://www.curseforge.com/minecraft/mc-mods/thermal-expansion) to be installed to show the recipes.

However, I mentioned into my list that I should add a notice that there is no recipe until the mod is added into the modpack, thank you.
