### ISSUE TITLE
Can't upgrade Energetic Angel Ring?

### ISSUE THREAD

**Issue by Moj-FPS** [DenisMasterHerobrine/AngelRing#54]
I'm a little confused, I upgraded the Angel Ring directly to the Energetic Angel Ring, but now I can't upgrade it to anything else. In order to the upgrade to the Hardened Angel Ring, it only accepts the Leadstone Angel Ring, which has less FE than the Energetic Angel Ring. Am I doing something wrong here, or is this just bugged?

Thanks in advance

**Comment by DenisMasterHerobrine** [comment]
Hello! This is intended, but due to a bit of confusion, I'm going to add a new recipe which allows to use Energetic Angel Ring to craft the Thermal Expansion's equivalents for the ring. Originally Energetic Angel Ring meant to be used if there is no Thermal Series mods, but there are any mod that allows you to charge items with FE.

In the original idea, the "energetic" rings should appear only and only if there's any mod that provides FE/RF and then provide respective Angel Rings and only if there's any recipes available to craft them.

As for now, I'll leave this issue open, because there isn't any real way in-game to transform the "vanilla-styled" ring into Thermal Series ones.

**Comment by MojtabaiGaming** [comment]
Thanks for the reply, I appreciate the explanation. That makes much more sense now. I set up a Flux Network to keep the Energetic Ring charged because I was way too lazy to go out and look for another Elytra to remake the ring 😂 So I don’t think I’ll have any issues keeping it good and charged. I do love the mod though, so thanks for your work and once again I appreciate the response!On Feb 29, 2024, at 5:36 AM, DenisMasterHerobrine ***@***.***> wrote:﻿
Hello! This is intended, but due to a bit of confusion, I'm going to add a new recipe which allows to use Energetic Angel Ring to craft the Thermal Expansion's equivalents for the ring. Originally Energetic Angel Ring meant to be used if there is no Thermal Series mods, but there are any mod that allows you to charge items with FE.
In the original idea, the "energetic" rings should appear only and only if there's any mod that provides FE/RF and then provide respective Angel Rings and only if there's any recipes available to craft them.
As for now, I'll leave this issue open, because there isn't any real way in-game to transform the "vanilla-styled" ring into Thermal Series ones.

**Comment by DenisMasterHerobrine** [comment]
Should be fixed in v2.3.0 for MC 1.20.1.
